"""First migration

Revision ID: fa9b639a8730
Revises: 
Create Date: 2023-10-16 18:36:06.138883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9b639a8730'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('aircraft_id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('passenger_capacity', sa.Integer(), nullable=False),
    sa.Column('cruising_range_miles', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('aircraft_id')
    )
    op.create_table('airport',
    sa.Column('airport_id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('airport_name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('airport_id')
    )
    op.create_table('pilot',
    sa.Column('pilot_id', sa.Integer(), nullable=False, auto_incremenet=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('born_date', sa.Date(), nullable=False),
    sa.Column('flown_hours', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pilot_id')
    )
    op.create_table('route',
    sa.Column('route_id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('departure_airport_id', sa.Integer(), nullable=False),
    sa.Column('arrival_airport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arrival_airport_id'], ['airport.airport_id'], ),
    sa.ForeignKeyConstraint(['departure_airport_id'], ['airport.airport_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('flight',
    sa.Column('flight_id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.aircraft_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('flight_detail',
    sa.Column('flight_detail_ID', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.flight_id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilot.pilot_id'], ),
    sa.PrimaryKeyConstraint('flight_detail_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_detail')
    op.drop_table('flight')
    op.drop_table('route')
    op.drop_table('pilot')
    op.drop_table('airport')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
